import "./globals.css";

import type { Metadata } from "next";
import localFont from "next/font/local";

import Header from "./components/header/Header";
import SearchBar from "./components/search/SearchBar";

const pretendard = localFont({
	src: "./fonts/PretendardVariable.woff2",
	display: "swap",
	weight: "45 920",
	variable: "--font-pretendard",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="ko"
			className={`${pretendard.variable} flex justify-center bg-gray-600 `}
		>
			<body
				className={`${pretendard.className} flex flex-col w-[375px] bg-white min-h-[100dvh]`}
			>
				<Header />

				<main className="flex-1 w-[310px] py-3.5 m-auto">
					<div className="mt-4">
						<SearchBar />
					</div>
					{children}
				</main>
				<footer>푸터</footer>
			</body>
		</html>
	);
}
